// Archivo: medication-catalog.references.ts
// Ruta: apps/api/src/medication-catalog/medication-catalog.references.ts
// Funcion: Listas normalizadas y bibliografia del maestro farmacéutico.

export const PRODUCT_TYPES = [
  'MEDICAMENTO',
  'DISPOSITIVO_MEDICO',
  'PRODUCTO_SANITARIO',
  'MATERIAL_MEDICO',
  'COSMETICO',
  'OTRO',
] as const;

export const PHARMACEUTICAL_FORMS = [
  'TABLETA',
  'TABLETA RECUBIERTA',
  'TABLETA MASTICABLE',
  'TABLETA EFERVESCENTE',
  'TABLETA SUBLINGUAL',
  'TABLETA BUCODISPERSABLE',
  'TABLETA DE LIBERACION PROLONGADA',
  'CAPSULA',
  'CAPSULA BLANDA',
  'CAPSULA DE LIBERACION PROLONGADA',
  'COMPRIMIDO',
  'COMPRIMIDO RECUBIERTO',
  'GRAGEA',
  'POLVO',
  'POLVO PARA SOLUCION ORAL',
  'POLVO PARA SUSPENSION ORAL',
  'POLVO PARA SOLUCION INYECTABLE',
  'GRANULADO',
  'SOLUCION ORAL',
  'SUSPENSION ORAL',
  'JARABE',
  'GOTAS ORALES',
  'SOLUCION INYECTABLE',
  'SUSPENSION INYECTABLE',
  'CONCENTRADO PARA SOLUCION PARA PERFUSION',
  'CREMA',
  'GEL',
  'UNGÜENTO',
  'LOCION',
  'SOLUCION TOPICA',
  'AEROSOL',
  'SPRAY',
  'INHALADOR',
  'SOLUCION PARA INHALACION',
  'SUPOSITORIO',
  'OVULO',
  'PARCHE TRANSDERMICO',
  'SOLUCION OFTALMICA',
  'UNGÜENTO OFTALMICO',
  'SOLUCION OTICA',
  'SOLUCION NASAL',
  'GAS MEDICINAL',
  'IMPLANTE',
  'NO APLICA',
] as const;

export const ADMINISTRATION_ROUTES = [
  'ORAL',
  'SUBLINGUAL',
  'BUCAL',
  'INTRAVENOSA',
  'INTRAMUSCULAR',
  'SUBCUTANEA',
  'INTRADERMICA',
  'TOPICA',
  'TRANSDERMICA',
  'OFTALMICA',
  'OTICA',
  'NASAL',
  'INHALATORIA',
  'RECTAL',
  'VAGINAL',
  'URETRAL',
  'INTRAARTICULAR',
  'INTRATECAL',
  'EPIDURAL',
  'INTRAOSEA',
  'NO APLICA',
] as const;

export const UNIT_MEASURES = [
  'UNIDAD',
  'TABLETA',
  'CAPSULA',
  'COMPRIMIDO',
  'AMPOLLA',
  'VIAL',
  'FRASCO',
  'TUBO',
  'SOBRE',
  'BLISTER',
  'CAJA',
  'LATA',
  'BOLSA',
  'KIT',
  'DISPOSITIVO',
  'MILILITRO',
  'LITRO',
  'GRAMO',
  'KILOGRAMO',
] as const;

export const PHARMACY_CATALOG_REFERENCES = [
  {
    institution: 'DIGEMID - Ministerio de Salud del Peru',
    title: 'Estandares de Productos Farmaceuticos',
    use: 'Forma farmaceutica, via de administracion, unidad de medida y tipo de producto.',
    url: 'https://www.digemid.minsa.gob.pe/webDigemid/estandares-de-productos-farmaceuticos/',
    accessedAt: '2026-06-22',
  },
  {
    institution: 'DIGEMID - Ministerio de Salud del Peru',
    title: 'Registro Sanitario de Productos Farmaceuticos',
    use: 'Campos regulatorios del producto y registro sanitario.',
    url: 'https://www.digemid.minsa.gob.pe/webDigemid/registro-sanitario/productos-farmaceuticos/',
    accessedAt: '2026-06-22',
  },
  {
    institution: 'Organizacion Mundial de la Salud',
    title: 'Prequalification of Medical Products - Glossary',
    use: 'Definicion internacional de forma farmaceutica y producto terminado.',
    url: 'https://extranet.who.int/prequal/content/glossary',
    accessedAt: '2026-06-22',
  },
  {
    institution: 'European Directorate for the Quality of Medicines & HealthCare',
    title: 'Standard Terms Database',
    use: 'Terminologia normalizada de formas, vias y unidades de presentacion.',
    url: 'https://www.edqm.eu/en/standard-terms-database',
    accessedAt: '2026-06-22',
  },
] as const;
